{% set name = "pycentroids" %}
{% set version = "0.2.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8bacd9644c1d3fcf7be41fc670c9236a440a7c60d27b58aecc4ac450fdf89915

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [win]

requirements:
  build:
    - cmake
    - cpplint
    - make  # [linux]
    - pybind11
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - _openmp_mutex  # [linux]
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - numpy
    - pandas

test:
  requires:
    - pytest
    - scipy
  imports:
    - pycentroids
  commands:
    - pytest --pyargs pycentroids.tests

about:
  home: https://github.com/NSLS-II/centroids
  license: BSD-3-Clause
  license_file: LICENSE/LICENSE
  summary: Routines for performing single-photon counting and centroiding of CCD data

extra:
  recipe-maintainers:
    - mrakitin
    - conda-forge/event-model
